### ISSUE TITLE
3 Wizard | Question 1 - movie duration 

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project#2]
## Value Proposition

**As a** user

**I need** to select the length of the movie 

**to be able to** to find the running time suitable for my time 

## Description
	
![Bildschirmfoto 2022-12-09 um 14 58 59](https://user-images.githubusercontent.com/96984853/206718757-a38bfa9b-4e7e-4d03-9e8d-9b00d9ec966b.png)

## Acceptance Criteria
- [ ] There is a headline saying "Wie lange darf dein Film heute sein?"
- [ ] The user can choose between four options:  "möglichst kurz, normale Lauflänge, ich habe Zeit, ist mir egal"
- [ ]  After clicking the button the user will be redirected to the movie recommendation page, where a movie title with the running proper length is shown (no further styling) 
- [ ] on the main page the text link is changed to a button showing "Jetzt starten" which links to this wizard

## Tasks
- [ ] the question is located in a wizard parent component (app > main > wizard > questionDuration)
- [ ] Step 1: I use Mocked data - the array method is used to search through a test movie array with 10 movies
- [ ] the runtime is calculated on the duration field: - möglichst kurz (<100 Min), normale Lauflänge (100 - 140 Min), ich habe Zeit (>140 Min), ist mir egal (every movie)  
- [ ] after hitting one of the four options, the user is redirected to a dynamic URL, which is rendered by the movie slug

**Comment by marvinRoellecke** [comment]
Alles in allem super 👍 
Vielleicht kannst du noch in der Grafik kenntlich machen, welche Button in dieser US noch nicht bearbeitet werden.

**Comment by flipkoehler** [comment]
danke für das Feedback. Habe die Grafik mal ausgetauscht und ergänzt, dass man mit Klick auf das Logo wieder auf den Anfang kommt. 
Zu der Frage - jepp! den Wert gebe ich bei der Berechnung dann mit 👍
