### ISSUE TITLE
5 About Page & Navigation

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project#5]
## Value Proposition

**As a** user 

**I need** further information about movie flip 

**to be able to** understand the project

## Description
![Bildschirmfoto 2022-12-09 um 15 50 38](https://user-images.githubusercontent.com/96984853/206728609-883cde5e-914f-427e-8c24-ce6a79272a45.png)

## Acceptance Criteria
- [ ] there is a navigation at the bottom of the page, where I can choose between the main page and the about page
- [ ] the footer icon of the active page has an underline 
- [ ] on the detail page is a headline saying "Über Movie Flip" and an icon 
- [ ] there is content with icons describing the project 
- [ ] a click on the button "Kontakt aufnehmen" lets you send a mail to my contact

## Tasks

- [ ] the navigation should by flexibel within a component 
- [ ] the button has a mailto function
